package org.projects.TaskScheduler.models;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import java.time.LocalDateTime;
import java.util.List;
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "task")
public class Task {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String taskId;

    @DynamoDBAttribute
    private String taskName;

    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    private LocalDateTime scheduleTime;

    @DynamoDBAttribute
    private boolean completed;

    @DynamoDBAttribute
    private List<String> emails;

    public String getTaskId(){
        return taskId;
    }

    public String getTaskName(){
        return taskName;
    }

    public Boolean getIsCompleted(){
        return completed;
    }

    public String getDescription(){
        return description;
    }

    public LocalDateTime getScheduleTime(){
        return scheduleTime;
    }

    public List<String> getEmails(){
        return emails;
    }




}
