package org.projects.TaskScheduler.models;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;
import org.projects.TaskScheduler.config.LocalDateTimeConverter;

import java.time.LocalDateTime;
import java.util.List;
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "task")
public class Task {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String taskId;

    @DynamoDBAttribute
    private String taskName;

    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime scheduleTime;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime createdAt;

    @DynamoDBAttribute
    private boolean completed;

    @DynamoDBAttribute
    private List<String> emails;


}
